import { Category, Company, Product } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '1',
    company: Company.Sony,
    name: 'Bravia XR Series',
    category: Category.TV,
    specs: { screenSize: '55"' },
    price: 64990,
    stock: 12,
    description: 'Immersive 4K visuals with XR processor. Smart Google TV features included.',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '2',
    company: Company.LG,
    name: 'AI Dual Inverter',
    category: Category.AC,
    specs: { tonnage: '1.5 Ton' },
    price: 44500,
    stock: 4,
    description: 'Energy efficient cooling with AI convertible 6-in-1 cooling modes.',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '3',
    company: Company.Samsung,
    name: 'Curd Maestro',
    category: Category.Fridge,
    specs: { capacity: '253 L' },
    price: 26900,
    stock: 8,
    description: 'Frost-free double door fridge with digital inverter technology.',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '4',
    company: Company.Whirlpool,
    name: 'StainWash Pro',
    category: Category.WashingMachine,
    specs: { capacity: '7.5 Kg', type: 'Fully Automatic' },
    price: 18500,
    stock: 15,
    description: 'Hard water wash technology with 12 wash programs.',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '5',
    company: Company.Luminous,
    name: 'Zelio+ 1100',
    category: Category.Inverter,
    specs: { capacity: '900 VA' },
    price: 6500,
    stock: 10,
    description: 'Sine wave inverter with intelligent battery management.',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '6',
    company: Company.Luminous,
    name: 'Red Charge RC 18000',
    category: Category.Battery,
    specs: { capacity: '150 Ah' },
    price: 13500,
    stock: 6,
    description: 'Tall tubular battery suitable for deep discharge.',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '7',
    company: Company.Kent,
    name: 'Grand+',
    category: Category.WaterFilter,
    price: 15500,
    stock: 2,
    description: 'Mineral RO technology providing 100% safe and healthy water.',
    lastUpdated: new Date().toISOString(),
  }
];

export const LOW_STOCK_THRESHOLD = 5;